### ISSUE TITLE
Banner image not consuming complete space

### ISSUE THREAD

**Issue by devshiva619** [GirlScriptSummerOfCode/MakkalaJagriti#5]
*Brief*  
The image in the banner is not taking up the entire banner width.
The issue can be seen at [Link](http://www.makkalajagriti.org/youth/)
![screenshot of the issue](https://user-images.githubusercontent.com/20336672/42014454-0c2578a4-7ac0-11e8-943e-5a9ffbeb76ae.png)

**Comment by devshiva619** [comment]
I would like to work on the same.

**Comment by iamchathu** [comment]
@devshiva619 
please put this to issue #1
